### PR TITLE
Mapping from rosbag

### PR DESCRIPTION
**Pull request by facontidavide**
I noticed that the pf_slam2d has a fromRosbag method, but the other didn't.

I am suggesting this change, that allows rosbag to be used by both the mapping applications.

I decided to refactor it because it is important, in my opinion, to make the mapping process visible in RViz. For this reason:

- Important topics are republished, i.e. laser and TF
- **clock** is published and **use_sim_time** is set to true.
- ros::Time instead of ros::WallTime is used to publish the map as often as in real-time.
- README updated

The application is kept alive to give the opportunity to the user to call **map_saver**.

### CODE REVIEW

**Comment by facontidavide** [comment]
I also find the log particularly satisfactory...
```

[ INFO] [1571408440.080871173]: Online SLAM node up and running
[ INFO] [1571408440.082327219]: Subscribing to laser rosbag [/front_laser/scan]
[ INFO] [1571408440.082344794]: Running SLAM in Rosbag Mode (offline)
[ INFO] [1571408440.082377630]: Opening rosbag [/home/df/BAGS/filtered.bag]
[ INFO] [1571408440.090369590, 1571039963.925335488]: Laser is mounted upwards.
[ INFO] [1571408440.090405341, 1571039963.925335488]: New laser configured (id=0 frame_id=rslidar)
[ INFO] [1571408441.091361149, 1571040013.889048578]: Processing the rosbag at 50.1X speed.
[ INFO] [1571408442.100320155, 1571040044.430876883]: Processing the rosbag at 30.3X speed.
[ INFO] [1571408443.147757525, 1571040075.948066861]: Processing the rosbag at 30.1X speed.
[ INFO] [1571408444.151270878, 1571040115.588183829]: Processing the rosbag at 39.5X speed.
[ INFO] [1571408445.152892218, 1571040151.369832331]: Processing the rosbag at 35.7X speed.
[ INFO] [1571408446.155127309, 1571040190.648934180]: Processing the rosbag at 39.2X speed.
[ INFO] [1571408447.156722119, 1571040226.561054250]: Processing the rosbag at 35.8X speed.
[ INFO] [1571408448.174951327, 1571040258.306070440]: Processing the rosbag at 31.2X speed.
[ INFO] [1571408449.174954592, 1571040303.423481800]: Processing the rosbag at 45.1X speed.
[ INFO] [1571408450.209378917, 1571040347.427007340]: Processing the rosbag at 42.5X speed.
[ INFO] [1571408451.216838831, 1571040392.709658078]: Processing the rosbag at 45.0X speed.
[ INFO] [1571408451.628764646, 1571040430.508819485]: --------- Mapping Completed ---------
[ INFO] [1571408451.628792039, 1571040430.508819485]: Processed the rosbag at 40.5X speed.
[ INFO] [1571408451.628802085, 1571040430.508819485]: Number of processed Laserscan messages: 4669

```

**Comment by eupedrosa** [comment]
:+1: Having the mapping process in RViz is, indeed, very useful. During development I usually used `rosbag` replaying at a controlled rate so I could see what was happening.

@facontidavide, let me test your proposal against our rosbags to see if everything is working.

Addicionally, if you enjoyed the mapping speed, I known a way to make it a little bit more faster. There is a parameter that is not exposed in ROS called `truncated_ray`. This will tell the mapper to truncate the rays to the specified length. Just try adding the following line to the `Slam2DROS` or `PFSlam2DROS` constructor:
```c++
pnh_.param("truncated_ray", options.truncated_ray, 0.0);
```
Try setting the parameters for different values and check the results.

**Comment by facontidavide** [comment]
> During development I usually used rosbag replaying at a controlled rate so I could see what was happening.

As you can see in my log messages, the "optimal rate is actually variable, for this reason this PR is particularly useful ;)

Talking about performance, I noticed poor scalability of the pf_slam_2d application with the number of threads. But this is the subject for a future issue :D

**Comment by eupedrosa** [comment]
This PR works with a caveat: there must be at least one subscriber during mapping in order for the map to be published (and latched). Using RViz during mapping solves this problem.  I am OK with this behavior, I like to see the map being built. @facontidavide any thoughts?

> Talking about performance, I noticed poor scalability of the pf_slam_2d application with the number of threads. But this is the subject for a future issue :D

Please open an issue at https://github.com/iris-ua/iris_lama, I would love to discuss multi-threading.

**Comment by facontidavide** [comment]
It is indeed a problem, because I want to be able to get the map with **map_saver** even if RViz isn't used.

There must be at least a single latched map publish at the end of the rosbag replay

**Comment by facontidavide** [comment]
I have an idea, let me implement it...

**Comment by facontidavide** [comment]
Have a look to this solution:

https://github.com/facontidavide/iris_lama_ros/commit/a6f2beb83fde3bf43d5a73aa07ed78de5d12748e

PROS:

Even without RViz, user may call map_saver once the rosbag has been completely replayed

CONS:

Frequency of map publish is ros::WallTime and not simulated ros::Time. I liked the "accelerated" refresh rate.

A potential solution to the that would be to keep on publishing the **/clock** message to keep the spin alive.

What do you think?

**Comment by facontidavide** [comment]
Ok, I decided it myself... https://github.com/facontidavide/iris_lama_ros/commit/36e08eca713d127e1c44a2c0d900199325defdaa

**Comment by facontidavide** [comment]
# HUGE problem found

If the rosbag was compressed with LZ4, the application crash!

I believe that the problem is related to the embedded version of the lz4 library in **iris_lama*, that is not binary compatible with the on in **rosbag_storage**.

I am creating an issue on the other repository.

**Comment by eupedrosa** [comment]
That is not good. Is it on Kinetic or Melodic?
> I believe that the problem is related to the embedded version of the lz4 library in *iris_lama, that is not binary compatible with the on in rosbag_storage.

That is most likely the cause. I will try to find a solution.

**Comment by eupedrosa** [comment]
> UPDATED
> 
> Have a look to this branch.
> 
> https://github.com/facontidavide/iris_lama_ros/tree/fix_map_publishing

:+1: to the virtual clock. I like the solution. @facontidavide  can you add it to this PR?

**Comment by facontidavide** [comment]
I will do some cleanup. I will tell you once it is ready to merge

**Comment by facontidavide** [comment]
Ok! I have done a lot of cleanup of the code and I like it much more.

Summarizing:

if launched with "Robag Mode", maps are published only if there is at least 1 subscriber, but at the end of the rosbag, they are published for sure at least once, to give the opportunity to map_saver to record the map. 

If it is ok, for you, we can merge this. unfortunately I did NOT find a way to detect if the rosbag is compressed with LZ4, because the method `Bag::getCompression` refers only to writing, not reading :( 

ready to merge in my opinion

**Comment by facontidavide** [comment]
Follow up about the LZ4 issue:

The exact code, when not linked to iris_lama, works fine, but crash when linked.

**Pull request merged**
