### PR TITLE
Support for ROS 2 jazzy

### PR DESCRIPTION
**Pull request by suo235**
## Overview
Eliminated errors and warnings when building with ROS 2 Jazzy.

## Changes
- Replaced deprecated APIs with the latest one
- Suppressed compiler's warnings

## Future Tasks
- Support for launching SLAM nodes as composable
- Implementation of Graph SLAM (now testing on Raspberry Pi 5)

### CODE REVIEW

**Comment by eupedrosa** [comment]
Hi @suo235

Thank you for the contribution. 

This PR was tested against the latest version of [iris_lama](https://github.com/iris-ua/iris_lama)?

**Comment by suo235** [comment]
Dear @eupedrosa 

First of all, I appreciate your team's hard work on the great LaMa library.

Yes, I tested slam2d, pf_slam2d and loc2d against the latest version of iris_lama.

But I did not notice that some parameter names in launch files was obsolete because I tested iris_lama_ros2's nodes without the launch files. So I fixed the launch files and tested above nodes again. Generated maps and localization results look fine!

**Comment by eupedrosa** [comment]
Sorry for the late reply.

I realy want to have a working version for ROS2. I will accept the PR. If it works as expected I will create a new branch for ROS2 based on your contributions.

**Comment by suo235** [comment]
Hi @eupedrosa 
Thank you for accepting my PR.
I recommend that you revert this PR AFTER you creare a new branch for ROS2. Because the latest eloquent-devel branch perhaps cause a build error against ROS2 Eloquent.

**Comment by eupedrosa** [comment]
Don't worry, we are not using ROS2 Eloquent.

**Pull request merged**
